//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DentalClinic {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ProjResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ProjResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DentalClinic.ProjResource", typeof(ProjResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap aloba {
            get {
                object obj = ResourceManager.GetObject("aloba", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap benigno {
            get {
                object obj = ResourceManager.GetObject("benigno", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Marie Santiago.
        /// </summary>
        internal static string dev1Name {
            get {
                return ResourceManager.GetString("dev1Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System Analyst.
        /// </summary>
        internal static string dev1Position {
            get {
                return ResourceManager.GetString("dev1Position", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alfred Philip Benigno.
        /// </summary>
        internal static string dev2Name {
            get {
                return ResourceManager.GetString("dev2Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System Analyst.
        /// </summary>
        internal static string dev2Position {
            get {
                return ResourceManager.GetString("dev2Position", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Francesca Mandadero.
        /// </summary>
        internal static string dev3Name {
            get {
                return ResourceManager.GetString("dev3Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System Analyst.
        /// </summary>
        internal static string dev3Position {
            get {
                return ResourceManager.GetString("dev3Position", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Anton Aloba.
        /// </summary>
        internal static string dev4Name {
            get {
                return ResourceManager.GetString("dev4Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System Analyst.
        /// </summary>
        internal static string dev4Position {
            get {
                return ResourceManager.GetString("dev4Position", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap mandadero {
            get {
                object obj = ResourceManager.GetObject("mandadero", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap santiago {
            get {
                object obj = ResourceManager.GetObject("santiago", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
